Token
FedorovIgorFeliksovich/api_yamdb pull request #8
Opened 2023-02-02 17:35 UTC by FedorovIgorFeliksovich

Добавил Токен

2023-02-02 18:40 UTC, RomanTurundaev requested changes

2023-02-02 18:40 UTC, RomanTurundaev commented on api_yamdb/api_yamdb/settings.py
> +    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
То же что и выше

2023-02-02 18:40 UTC, RomanTurundaev commented on api_yamdb/api_yamdb/urls.py
> +    path('api/token/',
Мы движемся видимо не в ту сторону.
По ТЗ нам не надо генерировать новый токен, нам нужна проработка получения токена по username и коду подтверждения.

2023-02-03 13:58 UTC, amater95 approved these changes
Я посмотрел код, посмотрел видос по jwt токен, вроде все так

2023-02-03 14:07 UTC, amater95 commented on api_yamdb/api_yamdb/urls.py
> +    path('api/token/',
а блин не заметил... у нас ведь сейчас получается что токен выдается при отправке пары логин пароль, а нам надо через логин и ключ, который должен на почту придти...

2023-02-03 15:22 UTC, amater95 approved these changes

2023-02-03 15:44 UTC, RomanTurundaev approved these changes

2023-02-03 17:59 UTC, closed without merging